version: 2

sources:
  - name: sample
    description: This is a replica of the snowflake sample database used by our app.
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        description: One record per customer
      - name: orders
        description: One record per Order. Includes cancelled and deleted orders.
      
      - name: supplier
        description: Supplier record.      
    
      - name: part
        description: part record.
        
      - name: partsupp
        description: part-supplier record.