version: 2

models:
  - name: customers
    description: One record per customer.
    columns:
      - name: customer_id
        description: > 
          unique id for each customer. 
          The id is imported from source data system.
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  
  - name: stg_orders
    description: |
      ## This model cleans up orders data.
      * Temporary holding place for newly imported records from source.

    columns:
      - name: status
        tests:
          - accepted_values:
              values: ['placed','shipped','completed','return_pending','returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
          
          